- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repsitories
      zypper:
        update_cache: yes
      changed_when: false

  tasks:
    - include: tasks/packages.yml
